import { and, eq } from "drizzle-orm";
import { getAvatarUrl } from "@hackerspub/models/account";
import { getViewableArticleAnalyticsPostIds } from "@hackerspub/models/article-analytics";
import {
  getArticleDraftMediumUrls,
  getArticleSourceMediumUrls,
} from "@hackerspub/models/article";
import { getArticleTranslationDraftMediumUrls } from "@hackerspub/models/article-translation";
import {
  getDraftRevision,
  getSourceRevision,
} from "@hackerspub/models/article-revision";
import { renderCustomEmojis } from "@hackerspub/models/emoji";
import {
  addExternalLinkTargets,
  transformMentions,
} from "@hackerspub/models/html";
import { negotiateLocale } from "@hackerspub/models/i18n";
import { canAccountActAs } from "@hackerspub/models/organization";
import {
  getMissingArticleMediumLabel,
  renderMarkup,
} from "@hackerspub/models/markup";
import { articleContentTable } from "@hackerspub/models/schema";
import type { Uuid } from "@hackerspub/models/uuid";
import { Account } from "../account.ts";
import { builder, type UserContext } from "../builder.ts";
import { putArticleOgImage } from "../og.ts";
import { Reactable } from "../reactable.ts";
import {
  articleContentOgImageComplexity,
  isCensoredForViewer,
  Post,
  sanctionActorSelection,
} from "./core.ts";

export const ArticleContentProvenance = builder.enumType(
  "ArticleContentProvenance",
  {
    description:
      "How a published `ArticleContent` version was produced. Stored " +
      "explicitly so that deleting a translator account never relabels " +
      "human work as automatic and automatic jobs can refuse to overwrite " +
      "anything that is not `LLM`.",
    values: {
      HUMAN: {
        value: "human",
        description:
          "A person-supplied translation that did not start from an " +
          "automatic draft.",
      },
      LLM: {
        value: "llm",
        description:
          "An unreviewed automatic translation generated by the platform.",
      },
      LLM_REVIEWED: {
        value: "llm_reviewed",
        description:
          "A human-managed version that started from an automatic draft and " +
          "was reviewed before publication, so it should be presented as an " +
          "AI-assisted translation.",
      },
      UNKNOWN: {
        value: "unknown",
        description:
          "A protected legacy classification for a version whose provenance " +
          "cannot be established. It is treated as human-managed for the " +
          "purpose of automatic-translation guards.",
      },
    } as const,
  },
);

export const ArticleTranslationProvenance = builder.enumType(
  "ArticleTranslationProvenance",
  {
    description:
      "Where the starting text of a private `ArticleTranslationDraft` came " +
      "from. It is fixed when the draft is created and cannot be changed by " +
      "editing, so copying automatic text into a draft never silently turns " +
      "it into a person-supplied translation.",
    values: {
      HUMAN: {
        value: "human",
        description:
          "The translator started from an empty draft or wrote the text " +
          "themselves.",
      },
      LLM: {
        value: "llm",
        description:
          "The draft was seeded from an existing automatic translation (or " +
          "reopened from an AI-assisted published version).",
      },
      UNKNOWN: {
        value: "unknown",
        description:
          "The draft was reopened from a legacy published version whose " +
          "provenance is unknown; publishing it preserves that uncertainty.",
      },
    } as const,
  },
);

export const Article = builder.drizzleNode("postTable", {
  variant: "Article",
  description:
    "A long-form blog article written on this platform. Articles have a " +
    "title, year-based URL slug, and can have multiple `ArticleContent` " +
    "translations. Remote articles federated from other instances lack a " +
    "local `articleSource` and will have `null` for `slug`, `publishedYear`, and `tags`.",
  interfaces: [Post, Reactable],
  id: {
    column: (post) => post.id,
  },
  fields: (t) => ({
    // articleSource is only present for locally-authored articles. Articles
    // federated in from remote servers don't have one — the upstream
    // metadata lives on the post itself, not in our articleSource table —
    // so the fields below have to be nullable to represent that.
    sourceId: t.expose("articleSourceId", {
      type: "UUID",
      nullable: true,
      description:
        "The local source UUID for this article (`articleSourceTable.id`). " +
        "Non-null only for source-backed local articles (articles originally " +
        "composed on this instance). Use it when calling APIs that need to " +
        "resolve the article's attached media, e.g. `renderMarkdown` with " +
        "an `articleSourceId` argument for edit-time previews. `null` for " +
        "articles federated in from remote instances.",
    }),
    viewerCanViewAnalytics: t.loadable({
      type: "Boolean",
      description:
        "Whether the authenticated viewer may read this local article's " +
        "private analytics. This is `true` for the personal author, accepted " +
        "members of the organization author, and moderators; unauthenticated " +
        "viewers and remote articles receive `false`.",
      async load(postIds: Uuid[], ctx: UserContext): Promise<boolean[]> {
        if (ctx.account == null) return postIds.map(() => false);
        const viewablePostIds = await getViewableArticleAnalyticsPostIds(
          ctx.db,
          postIds,
          {
            accountId: ctx.account.id,
            moderator: ctx.account.moderator,
          },
        );
        return postIds.map((postId) => viewablePostIds.has(postId));
      },
      resolve: (post) => post.id,
    }),
    viewerCanManageTranslations: t.boolean({
      description:
        "Whether the authenticated viewer may manage this local article's " +
        "translations (the `translationDrafts` field and the translation " +
        "mutations). This is `true` for the personal author and accepted " +
        "members of the organization author; moderators, unauthenticated " +
        "viewers, and remote articles receive `false`.",
      select: {
        with: { articleSource: { columns: { accountId: true } } },
      },
      async resolve(post, _, ctx) {
        const accountId = post.articleSource?.accountId;
        if (ctx.account == null || accountId == null) return false;
        return await canAccountActAs(ctx.db, ctx.account, accountId);
      },
    }),
    publishedYear: t.int({
      nullable: true,
      description:
        "The year the article was first published, used as part of its " +
        "URL path (e.g., `/@alice/2024/my-article`). `null` for articles " +
        "federated in from remote instances.",
      select: {
        with: {
          articleSource: {
            columns: { publishedYear: true },
          },
        },
      },
      resolve: (post) => post.articleSource?.publishedYear ?? null,
    }),
    slug: t.string({
      nullable: true,
      description:
        "URL slug for the article, used together with `publishedYear` " +
        "to build its permalink. `null` for remote articles.",
      select: {
        with: {
          articleSource: {
            columns: { slug: true },
          },
        },
      },
      resolve: (post) => post.articleSource?.slug ?? null,
    }),
    tags: t.stringList({
      nullable: true,
      description:
        "Author-assigned tags for this article. `null` for articles " +
        "federated in from remote instances.  Empty when the post is " +
        "censored, or its author is hidden by a moderation sanction, and the viewer is neither the author nor a moderator, " +
        "since the tags are part of the censored content.",
      select: {
        columns: { censored: true, actorId: true },
        with: {
          actor: sanctionActorSelection,
          articleSource: {
            columns: { tags: true },
          },
        },
      },
      resolve: (post, _, ctx) => {
        if (isCensoredForViewer(post, ctx)) return [];
        return post.articleSource?.tags ?? null;
      },
    }),
    allowLlmTranslation: t.boolean({
      nullable: true,
      description:
        "Whether the author has enabled LLM-based translation for this " +
        "article. `null` for articles federated from remote instances.",
      select: {
        with: {
          articleSource: {
            columns: { allowLlmTranslation: true },
          },
        },
      },
      resolve: (post) => post.articleSource?.allowLlmTranslation ?? null,
    }),
    contents: t.field({
      type: [ArticleContent],
      description:
        "All available language versions of this article's content. " +
        "Pass `language` to get only the best-matching locale (BCP 47 " +
        "negotiation). Pass `includeBeingTranslated: true` to also include " +
        "language versions whose LLM translation is still in progress.  " +
        "Empty when the article is censored or its author is hidden by " +
        "a moderation sanction, and the viewer is neither " +
        "its author nor a moderator.",
      args: {
        language: t.arg({
          type: "Locale",
          required: false,
          description:
            "Preferred BCP 47 locale for content negotiation. Omit it to " +
            "return every eligible language version.",
        }),
        includeBeingTranslated: t.arg({
          type: "Boolean",
          required: false,
          defaultValue: false,
          description:
            "Whether to include language versions whose LLM translation is " +
            "still in progress. Defaults to `false`.",
        }),
      },
      complexity: (args) => ({
        field: 1,
        multiplier: args.language == null ? 10 : 1,
      }),
      select: (args) => ({
        columns: { actorId: true, censored: true },
        with: {
          actor: sanctionActorSelection,
          articleSource: {
            with: {
              contents: args.includeBeingTranslated
                ? {}
                : { where: { beingTranslated: false } },
            },
          },
        },
      }),
      resolve(post, args, ctx) {
        if (isCensoredForViewer(post, ctx)) return [];
        const contents = post.articleSource?.contents ?? [];
        if (args.language == null) return contents;
        const availableLocales = contents.map((c) => c.language);
        const selectedLocale = negotiateLocale(args.language, availableLocales);
        return contents.filter((c) => c.language === selectedLocale?.baseName);
      },
    }),
  }),
});

builder.drizzleObjectField(Article, "account", (t) =>
  t.field({
    // Federated remote articles don't carry an articleSource (see the
    // articleSource-backed fields on Article above), so the author has
    // to be nullable here too — for remote articles, callers should fall
    // back to the post-level actor.
    type: Account,
    nullable: true,
    select: (_, __, nestedSelection) => ({
      with: {
        articleSource: {
          with: {
            account: nestedSelection(),
          },
        },
      },
    }),
    resolve: (post) => post.articleSource?.account ?? null,
  }),
);

export const ArticleDraft = builder.drizzleNode("articleDraftTable", {
  variant: "ArticleDraft",
  description:
    "An unpublished article draft. A draft belongs to a workspace account: " +
    "the owner's personal account, or an organization whose accepted members " +
    "share it. Visible only to the owner and accepted organization members " +
    "(not even moderators can read them), and promoted to an `Article` via " +
    "the `publishArticleDraft` mutation.",
  // The `articleDraft` query already scopes lookups, but a draft's global ID
  // must not let anyone else read it via `node(id:)`. `canActAsAccount`
  // accepts the owner itself and accepted members of the owning organization.
  authScopes: (draft) => ({ canActAsAccount: draft.accountId }),
  runScopesOnType: true,
  id: {
    column: (draft) => draft.id,
  },
  fields: (t) => ({
    uuid: t.expose("id", { type: "UUID" }),
    title: t.exposeString("title"),
    content: t.expose("content", { type: "Markdown" }),
    contentHtml: t.field({
      type: "HTML",
      description:
        "The rendered HTML of the draft's markdown content. Draft media are " +
        "resolved to their object storage URLs; note that those URLs are not " +
        "access-controlled beyond being hard to guess, so a shared URL keeps " +
        "working for anyone who already has it.",
      select: {
        columns: {
          content: true,
        },
      },
      async resolve(draft, _, ctx) {
        const rendered = await renderMarkup(ctx.fedCtx, draft.content, {
          mediumUrls: await getArticleDraftMediumUrls(
            ctx.db,
            ctx.disk,
            draft.id,
          ),
          missingMediumLabel: getMissingArticleMediumLabel(
            ctx.account?.locales?.[0],
          ),
        });
        return addExternalLinkTargets(
          rendered.html,
          new URL(ctx.fedCtx.canonicalOrigin),
        );
      },
    }),
    tags: t.exposeStringList("tags"),
    language: t.expose("language", {
      type: "Locale",
      nullable: true,
      description:
        "The original language of this draft, chosen before translations are " +
        "added. It is `null` on legacy drafts until their next save. It is " +
        "not the published language: `publishArticleDraft` takes that " +
        "separately, though it should normally match.",
    }),
    revision: t.exposeInt("revision", {
      description:
        "Optimistic concurrency token. Send it back as the `revision` input " +
        "of `saveArticleDraft` (or `moveArticleDraftToOrganization` / " +
        "`publishArticleDraft`) to update this exact version; a mismatch is " +
        "reported as `ArticleDraftConflictError` instead of overwriting.",
    }),
    created: t.expose("created", { type: "DateTime" }),
    updated: t.expose("updated", { type: "DateTime" }),
    account: t.relation("account", {
      description:
        "The workspace account that owns this draft: a personal account, or " +
        "an organization whose accepted members can edit it.",
    }),
    creator: t.relation("creator", {
      nullable: true,
      description:
        "The personal account that created the draft. This is an editing " +
        "record, not an author credit, and it never changes. `null` only " +
        "after the creator's account was deleted.",
    }),
  }),
});

export class ArticleDraftConflictError extends Error {
  public readonly currentRevision: number;

  public constructor(currentRevision: number) {
    super(
      `The draft was modified by someone else (current revision: ${currentRevision}).`,
    );
    this.name = "ArticleDraftConflictError";
    this.currentRevision = currentRevision;
  }
}

builder.objectType(ArticleDraftConflictError, {
  name: "ArticleDraftConflictError",
  description:
    "Returned when a save, delete, move, or publish targets a draft revision " +
    "that no longer matches the stored one, e.g. because another member saved " +
    "first. `currentRevision` is the revision the server currently holds; " +
    "reload the draft or retry the operation against that revision. The client " +
    "must not discard its local text automatically.",
  fields: (t) => ({
    currentRevision: t.exposeInt("currentRevision", {
      description: "The revision currently stored on the server.",
    }),
  }),
});

export const ArticleTranslationPublicationState = builder.enumType(
  "ArticleTranslationPublicationState",
  {
    description:
      "Publication state of a private `ArticleTranslationDraft`, kept separate " +
      "from source-review state so a draft can be both published and stale.",
    values: {
      UNPUBLISHED: {
        description:
          "No public version exists for this language yet; publishing the " +
          "draft would add a new language version.",
      },
      PUBLISHED: {
        description:
          "A public version exists and this draft revision is the one that " +
          "was published.",
      },
      PUBLISHED_WITH_CHANGES: {
        description:
          "A public version exists but the draft has private changes " +
          "(title, body, credit, or baseline) that are not public yet.",
      },
    } as const,
  },
);

export const ArticleTranslationDraft = builder.drizzleObject(
  "articleTranslationDraftTable",
  {
    name: "ArticleTranslationDraft",
    description:
      "A private, language-specific translation draft attached to an article " +
      "draft or a published article. It is never public: readers keep seeing " +
      "the last published version (or nothing) until it is published. Reach " +
      "it through `ArticleDraft.translationDrafts` or " +
      "`Article.translationDrafts`; it has no `node(id:)` entry point.",
    fields: (t) => ({
      uuid: t.expose("id", { type: "UUID" }),
      language: t.expose("language", {
        type: "Locale",
        description: "BCP 47 language tag of this translation.",
      }),
      title: t.exposeString("title", {
        description:
          "The translation's title. Empty while the translator has not " +
          "written one; such a draft is not ready to publish.",
      }),
      content: t.expose("content", { type: "Markdown" }),
      contentHtml: t.field({
        type: "HTML",
        description:
          "Rendered HTML of the translation draft, with both its own and the " +
          "parent's media resolved. Draft media URLs are not access-controlled " +
          "beyond being hard to guess, so a shared URL keeps working.",
        select: { columns: { content: true } },
        async resolve(draft, _, ctx) {
          const rendered = await renderMarkup(ctx.fedCtx, draft.content, {
            mediumUrls: await getArticleTranslationDraftMediumUrls(
              ctx.db,
              ctx.disk,
              draft,
            ),
            missingMediumLabel: getMissingArticleMediumLabel(
              ctx.account?.locales?.[0],
            ),
          });
          return addExternalLinkTargets(
            rendered.html,
            new URL(ctx.fedCtx.canonicalOrigin),
          );
        },
      }),
      translator: t.relation("translator", {
        nullable: true,
        description:
          "The account credited as the translator of this draft. It defaults " +
          "to the author for a personal original or the authenticated " +
          "individual for an organization, and is not changed by a later " +
          "editor's save. `null` after the credited account is deleted.",
      }),
      provenance: t.expose("provenance", {
        type: ArticleTranslationProvenance,
        description:
          "Where the starting text came from. Fixed at creation, so copying " +
          "an automatic translation into a draft cannot later be presented as " +
          "person-supplied.",
      }),
      revision: t.exposeInt("revision", {
        description:
          "Optimistic concurrency token, independent per language. Send it to " +
          "`saveArticleTranslationDraft` to reject a concurrent edit instead " +
          "of overwriting it.",
      }),
      publishedRevision: t.exposeInt("publishedRevision", {
        nullable: true,
        description:
          "The draft revision last published, or `null` if never published. " +
          "Compare with `revision` for a precise unpublished-changes check.",
      }),
      publicationState: t.field({
        type: ArticleTranslationPublicationState,
        description:
          "Whether a public version exists and whether this draft has " +
          "unpublished changes.",
        resolve: async (draft, _, ctx) => {
          if (draft.sourceId == null) return "UNPUBLISHED";
          const published = await ctx.db.query.articleContentTable.findFirst({
            where: {
              sourceId: draft.sourceId,
              language: draft.language,
            },
            columns: { language: true },
          });
          if (published == null) return "UNPUBLISHED";
          return draft.publishedRevision === draft.revision
            ? "PUBLISHED"
            : "PUBLISHED_WITH_CHANGES";
        },
      }),
      sourceChanged: t.field({
        type: "Boolean",
        description:
          "Whether the original has changed since the revision this draft " +
          "was based on (or its baseline is unknown). A `true` value means " +
          "publishing now would not mark the translation as current with the " +
          "latest original.",
        resolve: async (draft, _, ctx) => {
          if (draft.sourceRevisionId == null) return true;
          const baseline =
            await ctx.db.query.articleSourceRevisionTable.findFirst({
              where: { id: draft.sourceRevisionId },
            });
          const current =
            draft.articleDraftId != null
              ? await getDraftRevision(ctx.db, draft.articleDraftId)
              : draft.sourceId != null
                ? await getSourceRevision(ctx.db, draft.sourceId)
                : undefined;
          if (baseline == null || current == null) return true;
          // Compare content, not just ids: a reparented or re-created snapshot
          // with identical text is still current.
          return (
            baseline.language !== current.language ||
            baseline.title !== current.title ||
            baseline.content !== current.content
          );
        },
      }),
      created: t.expose("created", { type: "DateTime" }),
      updated: t.expose("updated", { type: "DateTime" }),
    }),
  },
);

builder.drizzleObjectField(ArticleDraft, "translationDrafts", (t) =>
  t.field({
    type: [ArticleTranslationDraft],
    description:
      "Private translation drafts owned by this article draft, one per " +
      "language. They are visible only to the workspace's authorized editors " +
      "and are published through `publishArticleDraft` or " +
      "`publishArticleTranslation`.",
    select: {
      with: { translationDrafts: { orderBy: { language: "asc" } } },
    },
    resolve: (draft) => draft.translationDrafts,
  }),
);

builder.drizzleObjectField(Article, "translationDrafts", (t) =>
  t.field({
    type: [ArticleTranslationDraft],
    description:
      "Private translation drafts attached to this published article, one per " +
      "language. Visible only to the author and accepted organization " +
      "members; remote articles and unauthorized viewers receive an empty " +
      "list. Readers keep seeing `contents` until a draft is published.",
    select: {
      with: {
        articleSource: {
          with: {
            translationDrafts: { orderBy: { language: "asc" } },
          },
        },
      },
    },
    async resolve(post, _, ctx) {
      const source = post.articleSource;
      if (source == null) return [];
      if (
        ctx.account == null ||
        !(await canAccountActAs(ctx.db, ctx.account, source.accountId))
      ) {
        return [];
      }
      return source.translationDrafts;
    },
  }),
);

/**
 * Whether this article content version belongs to a censored article whose
 * content must be redacted for the current viewer (the author and
 * moderators are exempt). Guards direct `ArticleContent` node access,
 * which bypasses `Article.contents`.
 */
function isArticleContentCensoredForViewer(
  content: { source: { post: { censored: Date | null; actorId: Uuid } } },
  ctx: UserContext,
): boolean {
  return isCensoredForViewer(content.source.post, ctx);
}

export const ArticleContent = builder.drizzleNode("articleContentTable", {
  name: "ArticleContent",
  description:
    "A single language version of an `Article`'s content. Each language is " +
    "stored separately; `Article.contents` lists all available translations. " +
    "Translated versions have a non-null `originalLanguage`; `translator` " +
    "can be `null` when the translating account was deleted.",
  id: {
    column: (content) => [content.sourceId, content.language],
  },
  fields: (t) => ({
    language: t.expose("language", {
      type: "Locale",
      description: "BCP 47 language tag identifying this content version.",
    }),
    title: t.field({
      type: "String",
      description:
        "The article's title in this language.  Empty when the article " +
        "is censored, or its author is hidden by a moderation sanction, " +
        "and the viewer is neither the author nor a " +
        "moderator.",
      select: {
        columns: { title: true },
        with: {
          source: {
            with: {
              post: {
                columns: { censored: true, actorId: true },
                with: { actor: sanctionActorSelection },
              },
            },
          },
        },
      },
      resolve: (content, _, ctx) =>
        isArticleContentCensoredForViewer(content, ctx) ? "" : content.title,
    }),
    summary: t.field({
      type: "String",
      nullable: true,
      select: {
        columns: { summary: true },
        with: {
          source: {
            with: {
              post: {
                columns: { censored: true, actorId: true },
                with: { actor: sanctionActorSelection },
              },
            },
          },
        },
      },
      resolve: (content, _, ctx) =>
        isArticleContentCensoredForViewer(content, ctx)
          ? null
          : content.summary,
      description:
        "`null` when the article is censored, or its author is hidden by " +
        "a moderation sanction, and the viewer is neither " +
        "its author nor a moderator.  Otherwise the " +
        "LLM-generated summary for this language version: `null` until " +
        "generation completes. Check `summaryStarted` to distinguish " +
        'between "not requested" and "in progress".',
    }),
    summaryStarted: t.expose("summaryStarted", {
      type: "DateTime",
      nullable: true,
      description:
        "When LLM summary generation was started for this content version. " +
        "`null` if summary generation has not been requested.",
    }),
    content: t.field({
      type: "HTML",
      description:
        "Rendered HTML of this language version, with media URLs resolved " +
        "and external links annotated.  Empty when the article is " +
        "censored, or its author is hidden by a moderation sanction, and the viewer is neither the author nor a moderator.",
      select: {
        columns: {
          content: true,
          language: true,
        },
        with: {
          source: {
            with: {
              post: {
                columns: {
                  actorId: true,
                  censored: true,
                  emojis: true,
                  tags: true,
                },
                with: {
                  actor: sanctionActorSelection,
                  mentions: {
                    with: { actor: true },
                  },
                },
              },
            },
          },
        },
      },
      async resolve(content, _, ctx) {
        if (isArticleContentCensoredForViewer(content, ctx)) return "";
        const html = await renderMarkup(ctx.fedCtx, content.content, {
          kv: ctx.kv,
          mediumUrls: await getArticleSourceMediumUrls(
            ctx.db,
            ctx.disk,
            content.sourceId,
          ),
          missingMediumLabel: getMissingArticleMediumLabel(content.language),
        });
        const post = content.source.post;
        let rendered = renderCustomEmojis(html.html, post.emojis);
        rendered = transformMentions(rendered, post.mentions, post.tags);
        return addExternalLinkTargets(
          rendered,
          new URL(ctx.fedCtx.canonicalOrigin),
        );
      },
    }),
    rawContent: t.field({
      type: "Markdown",
      description:
        "The raw markdown content for editing.  Empty when the article " +
        "is censored, or its author is hidden by a moderation sanction, " +
        "and the viewer is neither the author nor a " +
        "moderator.",
      select: {
        columns: { content: true },
        with: {
          source: {
            with: {
              post: {
                columns: { censored: true, actorId: true },
                with: { actor: sanctionActorSelection },
              },
            },
          },
        },
      },
      resolve(content, _, ctx) {
        if (isArticleContentCensoredForViewer(content, ctx)) return "";
        return content.content;
      },
    }),
    toc: t.field({
      type: "JSON",
      description:
        "Table of contents for the article content.  Empty when the " +
        "article is censored, or its author is hidden by a moderation " +
        "sanction, and the viewer is neither the author nor a " +
        "moderator.",
      select: {
        columns: { content: true, language: true, sourceId: true },
        with: {
          source: {
            with: {
              post: {
                columns: { censored: true, actorId: true },
                with: { actor: sanctionActorSelection },
              },
            },
          },
        },
      },
      async resolve(content, _, ctx) {
        if (isArticleContentCensoredForViewer(content, ctx)) return [];
        const rendered = await renderMarkup(ctx.fedCtx, content.content, {
          kv: ctx.kv,
          mediumUrls: await getArticleSourceMediumUrls(
            ctx.db,
            ctx.disk,
            content.sourceId,
          ),
          missingMediumLabel: getMissingArticleMediumLabel(content.language),
        });
        return rendered.toc;
      },
    }),
    originalLanguage: t.expose("originalLanguage", {
      type: "Locale",
      nullable: true,
      description:
        "The source language this content was translated from. Non-null for " +
        "every translated version, whether human-written or automatic; `null` " +
        "for the original content.",
    }),
    provenance: t.expose("provenance", {
      type: ArticleContentProvenance,
      nullable: true,
      description:
        "How this version was produced. `null` for the original-language " +
        "content. Use this rather than `translator` to decide whether a " +
        "version is automatic, human, or AI-assisted: the account reference " +
        "can become `null` when its account is deleted, but the provenance " +
        "does not change.",
    }),
    translator: t.relation("translator", {
      nullable: true,
      description:
        "The account credited as the translator of this version. For a " +
        "human-managed translation this is the credited individual; for an " +
        "automatic translation it is `null` (use `translationRequester` " +
        "instead). `null` for original content and after the account is " +
        "deleted; `provenance` remains authoritative.",
    }),
    translationRequester: t.relation("translationRequester", {
      nullable: true,
      description:
        "The account that requested an automatic translation. Non-null only " +
        "for an unreviewed `LLM` version; human-managed versions have a " +
        "`translator` and `null` here.",
    }),
    beingTranslated: t.exposeBoolean("beingTranslated", {
      description:
        "Whether an LLM translation into this language is currently " +
        "in progress. When `true`, the content may be incomplete.",
    }),
    updated: t.expose("updated", { type: "DateTime" }),
    published: t.expose("published", { type: "DateTime" }),
    ogImageUrl: t.field({
      type: "URL",
      nullable: true,
      description:
        "The generated Open Graph preview image for this language " +
        "version.  `null` when the article is censored, or its author is " +
        "hidden by a moderation sanction, and the viewer " +
        "is neither its author nor a moderator: the image is rendered " +
        "from the title and excerpt and would otherwise leak censored " +
        "content.",
      complexity: articleContentOgImageComplexity,
      select: {
        columns: {
          content: true,
          language: true,
          ogImageKey: true,
          sourceId: true,
          summary: true,
          title: true,
        },
        with: {
          source: {
            with: {
              account: {
                with: {
                  actor: {
                    columns: {
                      handleHost: true,
                    },
                  },
                  avatarMedium: true,
                  emails: true,
                },
              },
              post: {
                columns: { censored: true, actorId: true },
                with: { actor: sanctionActorSelection },
              },
            },
          },
        },
      },
      async resolve(content, _, ctx) {
        if (isArticleContentCensoredForViewer(content, ctx)) return null;
        const account = content.source.account;
        const rendered = await renderMarkup(ctx.fedCtx, content.content, {
          kv: ctx.kv,
          mediumUrls: await getArticleSourceMediumUrls(
            ctx.db,
            ctx.disk,
            content.sourceId,
          ),
          missingMediumLabel: getMissingArticleMediumLabel(content.language),
        });
        const avatarUrl = await getAvatarUrl(ctx.disk, account);
        const key = await putArticleOgImage(ctx.disk, content.ogImageKey, {
          authorName: account.name,
          avatarKey: account.avatarMedium?.key ?? avatarUrl,
          avatarUrl,
          excerpt: content.summary ?? rendered.text,
          handle: `@${account.username}@${account.actor.handleHost}`,
          language: content.language,
          sourceId: content.sourceId,
          title: content.title,
        });
        if (key !== content.ogImageKey) {
          await ctx.db
            .update(articleContentTable)
            .set({ ogImageKey: key })
            .where(
              and(
                eq(articleContentTable.sourceId, content.sourceId),
                eq(articleContentTable.language, content.language),
              ),
            );
        }
        return new URL(await ctx.disk.getUrl(key));
      },
    }),
    url: t.field({
      type: "URL",
      description:
        "Canonical URL for this language version. For the article's " +
        "primary language this is `/@username/year/slug`; for other " +
        "language versions it appends `/{language}` to that path.",
      select: {
        with: {
          source: {
            columns: {
              publishedYear: true,
              slug: true,
            },
            with: {
              account: {
                columns: {
                  username: true,
                },
              },
              post: {
                columns: {
                  language: true,
                },
              },
            },
          },
        },
      },
      resolve(content, _, ctx) {
        if (
          content.originalLanguage != null ||
          content.language !== content.source.post.language
        ) {
          return new URL(
            `/@${content.source.account.username}/${content.source.publishedYear}/${content.source.slug}/${content.language}`,
            ctx.fedCtx.canonicalOrigin,
          );
        }
        return new URL(
          `/@${content.source.account.username}/${content.source.publishedYear}/${content.source.slug}`,
          ctx.fedCtx.canonicalOrigin,
        );
      },
    }),
  }),
});
