const HEADING_SELECTOR = [1, 2, 3, 4, 5, 6]
  .map((level) => `.prose h${level}[id]`)
  .join(", ");

const EXISTING_ANCHOR_SELECTOR = ":scope > a.header-anchor";
const GENERATED_ANCHOR_ATTRIBUTE = "data-hackerspub-generated";
const GENERATED_ANCHOR_SELECTOR =
  `:scope > a.header-anchor[${GENERATED_ANCHOR_ATTRIBUTE}]`;
const ALL_GENERATED_ANCHORS_SELECTOR =
  `a.header-anchor[${GENERATED_ANCHOR_ATTRIBUTE}]`;
const ANCHOR_LABEL = "Link to this section";

/**
 * Reconciles permalink controls for identified Markdown headings.
 *
 * A fragment identifies an element in the whole document, not within its
 * `.prose` container.  Timeline cards can therefore make otherwise valid
 * remote heading IDs ambiguous.  Only document-unique IDs receive a control,
 * and controls generated by this function are removed if a later DOM update
 * introduces a duplicate.
 */
export function addHeaderAnchorLinks(document: Document): void {
  const headings = [
    ...document.querySelectorAll<HTMLElement>(HEADING_SELECTOR),
  ];
  const headingSet = new Set(headings);
  for (
    const anchor of document.querySelectorAll<HTMLAnchorElement>(
      ALL_GENERATED_ANCHORS_SELECTOR,
    )
  ) {
    const parent = anchor.parentElement as HTMLElement | null;
    if (parent == null || !headingSet.has(parent)) anchor.remove();
  }
  const idCounts = new Map<string, number>();
  for (const element of document.querySelectorAll<HTMLElement>("[id]")) {
    if (element.id === "") continue;
    idCounts.set(element.id, (idCounts.get(element.id) ?? 0) + 1);
  }

  for (const heading of headings) {
    const generatedAnchor = heading.querySelector<HTMLAnchorElement>(
      GENERATED_ANCHOR_SELECTOR,
    );
    if (heading.id === "" || idCounts.get(heading.id) !== 1) {
      generatedAnchor?.remove();
      continue;
    }
    if (generatedAnchor != null) {
      generatedAnchor.setAttribute(
        "href",
        `#${encodeURIComponent(heading.id)}`,
      );
      generatedAnchor.setAttribute("aria-label", ANCHOR_LABEL);
      generatedAnchor.title = ANCHOR_LABEL;
      heading.appendChild(generatedAnchor);
      continue;
    }
    if (heading.querySelector(EXISTING_ANCHOR_SELECTOR) != null) continue;

    const anchor = document.createElement("a");
    anchor.className = "header-anchor";
    anchor.setAttribute(GENERATED_ANCHOR_ATTRIBUTE, "");
    anchor.setAttribute("href", `#${encodeURIComponent(heading.id)}`);
    anchor.setAttribute("aria-label", ANCHOR_LABEL);
    anchor.title = ANCHOR_LABEL;
    heading.appendChild(anchor);
  }
}

/**
 * Installs progressive enhancement for Hackers' Pub-flavored Markdown.
 *
 * The initial scan handles server-rendered HTML.  Reconciliation after DOM
 * changes covers client-side route changes, previews, modals, and timeline
 * updates, including duplicates introduced or removed by those updates.
 */
export function installHeaderAnchorLinks(document: Document): () => void {
  addHeaderAnchorLinks(document);

  const MutationObserver = document.defaultView?.MutationObserver;
  if (MutationObserver == null) return () => {};

  const observe = () =>
    observer.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ["class", "id"],
      childList: true,
      subtree: true,
    });
  const observer = new MutationObserver(() => {
    // Avoid observing the anchors added or removed by reconciliation itself.
    observer.disconnect();
    addHeaderAnchorLinks(document);
    observe();
  });
  observe();
  return () => observer.disconnect();
}
